set_property PACKAGE_PIN AB22 [get_ports {Segment[0]}]
set_property PACKAGE_PIN AD24 [get_ports {Segment[1]}]
set_property PACKAGE_PIN AD23 [get_ports {Segment[2]}]
set_property PACKAGE_PIN Y21 [get_ports {Segment[3]}]
set_property PACKAGE_PIN W20 [get_ports {Segment[4]}]
set_property PACKAGE_PIN AC24 [get_ports {Segment[5]}]
set_property PACKAGE_PIN AC23 [get_ports {Segment[6]}]
set_property PACKAGE_PIN AA22 [get_ports {Segment[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Segment[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Segment[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Segment[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Segment[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Segment[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Segment[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Segment[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Segment[0]}]

set_property PACKAGE_PIN AD21 [get_ports {AN[0]}]
set_property PACKAGE_PIN AC21 [get_ports {AN[1]}]
set_property PACKAGE_PIN AB21 [get_ports {AN[2]}]
set_property PACKAGE_PIN AC22 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]

set_property PACKAGE_PIN AC18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]

set_property PACKAGE_PIN AA10 [get_ports SW]
set_property IOSTANDARD LVCMOS15 [get_ports SW]

set_property PACKAGE_PIN AF24 [get_ports Rc]
set_property IOSTANDARD LVCMOS33 [get_ports Rc]